typography_spectrum: 0.3168111671693623
color:
  brandStrength: 0.5145470702555031
  lightness: 0.38552631018683314
  saturation: 0.9464655155315995
  rhythmicContrast: 0.72413564263843
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
layout_spectrum: 0.2916997326537967
name: Point B Travels
navigation:
  - name: Tours and Airport Transfers
    url: 'http://pointbtransfers.com/'
    type: external
title: Discover Panama
description: Discover Panama in a unique way!
