typography_spectrum: 0.11927674687467515
color:
  brandStrength: 0.362538248533383
  lightness: 0.5130658086854964
  saturation: 0.5990062481723726
  rhythmicContrast: 0.09354017395526171
  brandColors:
    - '#004358'
    - '#1F8A70'
    - '#BEDB39'
    - '#FFE11A'
    - '#FD7400'
layout_spectrum: 0.20404529967345297
author:
  name: Alejandro
  email: ahepburn03@gmail.com
name: Mola Art Panama
navigation:
  - name: Tours and Airport Transfers
    url: 'http://pointbtransfers.com/'
    type: external
favicon: null
title: Mola art and souvenirs
description: Have fun discovering the beauties of Panama!
